---
# tasks file for elasticsearch

- name: Ajout de la clé apt
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Ajout du repo
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
    state: present
    update_cache: yes

- name: Install java8
  apt:
    name: default-jre
    state: present

- name: Install elasticsearch
  apt:
    name: elasticsearch
    state: present

- name: Hold elasticseach pkg version
  dpkg_selections:
    name: elasticsearch
    selection: hold

- name: Install elasticseach discovery-ec2
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin install discovery-ec2
  args:
    creates: /usr/share/elasticsearch/plugins/discovery-ec2/LICENSE.txt

- name: Install elasticseach lang-javascript
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin install lang-javascript
  args:
    creates: /usr/share/elasticsearch/plugins/lang-javascript/LICENSE.txt
- name: Deploy elasticsearch.yml
  template:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: restart elasticsearch

- name: Start elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Wait for everybody
  wait_for:
    host: "{{ansible_host}}"
    port: 9200
